### PR TITLE
Remove magni-base stop from fiducial follow

### PR DESCRIPTION
**Pull request by rohbotics**
This is no longer a step that we want to run.

https://forum.ubiquityrobotics.com/t/fiducial-follow-error/117/2

### CODE REVIEW

**Comment by davecrawley** [comment]
Is this just a documentation update?

David

**Comment by rohbotics** [comment]
Yes, the documentation was incorrect.

**Comment by jrlandau** [comment]
I am correcting it now

**Comment by rohbotics** [comment]
Joe this is a pull request, you can just merge it.

**Comment by rohbotics** [comment]
replaced by e2c62d99700ae1698485175c2efbbacbb8aa941c

**Pull request closed without merging**
