### PR TITLE
Update Loki Documentation for January Image

### PR DESCRIPTION
**Pull request by rohbotics**

### CODE REVIEW

**Comment by rohbotics** [comment]
Note for testing: you need to replace the wget command with 
`sudo wget https://raw.githubusercontent.com/UbiquityRobotics/learn/rohbotics-patch-1/quick_start/loki/loki-base -O /usr/sbin/loki-base`
because the PR is not merged yet, so the branch needs to be different.

**Comment by rohbotics** [comment]
Other than that note, the instructions seem to work ok for me on a fresh image. 

Go ahead and merge this once someone else tests it.

**Comment by rohbotics** [comment]
@waynegramlich Any luck testing this?

**Comment by waynegramlich** [comment]
I don't have a clue what this is about.  It is pretty hard for me to test.

**Comment by anfederman** [comment]
sudo service loki-base start
Failed to start loki-base.service: Unit loki-base.service not found.

no file in /etc/systemd/system,

unless you want the user to

sudo /usr/sbin/loki-base

**Comment by rohbotics** [comment]
Did you do step 5?

**Pull request merged**
